server:
  port: 8888
  servlet:
    context-path: /what-to-eat
spring:
  application:
    name: What to eat
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/what_to_eat
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true


