server:
  port: 8888
  contextPath: /what-to-eat
liquibase:
  change-log: classpath:/db/changelog-master.xml
spring:
  application:
    name: What to eat
  datasource:
    url: jdbc:mysql://localhost:3306/what_to_eat
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true


